
services:
  frontend:
    image: nginx:latest
    container_name: 5g-website
    ports:
      - "3306:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - 5g_platform
    depends_on:
      - backend

  backend:
    image: node:20
    container_name: 5g-backend
    working_dir: /app
    volumes:
      - ./backend:/app/backend
      - /app/node_modules
      - ./.env:/app/.env
      
    command: >
      sh -c "npm install && npm run start"
    ports:
      - "12345:12345"
    networks:
      - 5g_platform

networks:
  5g_platform:
    driver: bridge
