version: "3.9"

services:
  frontend:
    image: nginx:latest
    container_name: 5g-website
    ports:
      - "3306:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - 5g_platform
    depends_on:
      - backend

  backend:
    images: node:20
    container_name: 5g-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules   # ป้องกัน node_modules overwrite
    ports:
      - "12345:12345"
    networks:
      - 5g_platform

networks:
  5g_platform:
    driver: bridge
