version: "3.9"

services:
  frontend:
    image: nginx:latest
    container_name: 5g-website
    ports:
      - "3306:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - 5g_platform
    depends_on:
      - backend

  backend:
    image: node:18
    container_name: 5g-backend
    working_dir: /app
    
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env   # ✔ ต้องระบุ path:containerPath
    
    command: ["npm", "start"]
    
    ports:
      - "12345:12345"
    networks:
      - 5g_platform

networks:
  5g_platform:
    name: 5g-platform-network   # ✔ network name ตามที่ต้องการ
    driver: bridge
