name: Push-to-ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push-to-ec2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}

          SOURCE: "./"
          TARGET: "/home/ec2-user/5G-freelerning/Free-learning-5G"

          SCRIPT_AFTER: |
            cd /home/ec2-user/5G-freelerning/Free-learning-5G
            echo "Cleaning old frontend build..."
            rm -rf frontend/dist

            echo "Installing all dependencies..."
            npm install
            
            echo "Building frontend..."
            sudo npm run build -w frontend

            echo "Restarting Docker..."
            docker compose down || true
            docker compose up -d --build

            echo "Deployment complete!"
