name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # 1) ส่งไฟล์ทั้งหมดขึ้น EC2
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: "./"
          TARGET: "/home/ec2-user/5G-freelerning/Free-learning-5G"

      # 2) รันคำสั่งบน EC2 (build + restart docker)
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR="/home/ec2-user/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 20

            cd /home/ec2-user/5G-freelerning/Free-learning-5G
            nvm use 20
            echo "Cleaning old frontend build..."
            sudo rm -rf frontend/dist || true

            echo "Installing dependencies..."
            sudo npm install

            echo "Building frontend..."
            sudo npm run build -w frontend

            echo "Restarting docker..."
            docker-compose down || true
            docker-compose up -d --build

            echo "Deployment complete!"
