name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # 1) Upload files to EC2
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: "./"
          TARGET: "/home/ec2-user/5G-freelerning/Free-learning-5G"

      # 2) Build + restart Docker
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            **sudo chown -R ec2-user:ec2-user .**
            export NVM_DIR="/home/ec2-user/.nvm"
            source "$NVM_DIR/nvm.sh"
            nvm use 20

            echo "=== DEBUG CHECK ==="
            which node
            which npm
            node -v
            npm -v

            cd /home/ec2-user/5G-freelerning/Free-learning-5G
            

            echo "Installing frontend dependencies (Node 20)..."
            npm install

            echo "Building frontend..."
            npm run build -w frontend

            echo "Restarting docker..."
            docker-compose down || true
            docker-compose up -d --build

            echo "Deployment complete!"
