name: Push-to-ec2

#trigger deployment only on push to main branch

on:
  push:
    branch:
      - main

jobs:
  deploy:
    name: Push-to-ec2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: deploy to ec2 instant
        uses: easingthemes/ssh-dwploy@2.1.5
        env:
          
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}     # private key จาก GitHub Secrets
          REMOTE_HOST: ${{ secrets.EC2_HOST }}            # IP หรือ Domain
          REMOTE_USER: ${{ secrets.USERNAME }}            # หรือ ec2-user (ถ้า Amazon Linux)
          
          # ไฟล์/โฟลเดอร์บน GitHub ที่ต้องการส่งขึ้น EC2
          SOURCE: "./"

          # โฟลเดอร์ปลายทางบน EC2
          TARGET: "/home/ec2-user/5G-freelerning/Free-learning-5G"

          # หลัง deploy สั่ง restart ระบบ
          SCRIPT_AFTER: |
            cd /home/ec2-user/5G-freelerning/Free-learning-5G

            echo "Cleaning old frontend build..."
            rm -rf frontend/dist

            echo "installing all dependencies..."
            npm install
            
            echo "build new front/dist"
            sudo npm run build -w frontend

            echo "Restarting Docker..."
            docker compose down || true
            docker compose up -d --build

            echo "Deployment complete!"


